services:
  - type: web
    name: meu-app-docker
    env: docker
    plan: starter
    dockerfilePath: Dockerfile
    branch: main
    autoDeploy: true
    envVars:
      - key: APP_NAME
        value: Laravel
      - key: APP_ENV
        value: local
      - key: APP_KEY
        value: base64:mr2+DnCfXEarOeHWmdWPPpLu6Jz9bNteQO9GTwjSfVo=
      - key: APP_DEBUG
        value: 'true'
      - key: APP_URL
        value: http://localhost
    ports:
      - 8000
