
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: portifolio
    volumes:
      - .:/var/www
    ports:
      - "8000:8000"
    working_dir: /var/www
    command: php artisan serve --host=0.0.0.0 --port=8000
    networks:
      - laravel

  db:
    image: postgres:16
    container_name: portifolio-db
    restart: always
    environment:
      POSTGRES_DB: portifolio
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - laravel

volumes:
  pgdata:

networks:
  laravel:
    driver: bridge
