services:
  - type: web
    name: Portifolio_docker
    runtime: docker
    repo: https://github.com/DevJhoow/Portifolio
    branch: main
    dockerfilePath: Dockerfile
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_KEY
        generateValue: true
      - key: DB_CONNECTION
        value: sqlite
